### PR TITLE
Pass client vs. url/token into build report fn

### PR DESCRIPTION
**Pull request by MrCreosote**
Allows client to be mocked so build_report_view_data can be unit tested

### CODE REVIEW

**Comment by MrCreosote** [comment]
`test_create_static_narrative_ok_unit` fails because it expects a file to exist in `test/data` that doesn't

**Comment by MrCreosote** [comment]
Test fails due to
```
$ make sdkbase

make: *** No rule to make target 'sdkbase'.  Stop.
```
Is this due to @ialarmedalien 's changes?

**Comment by briehl** [comment]
> Test fails due to
> 
> ```
> $ make sdkbase
> 
> make: *** No rule to make target 'sdkbase'.  Stop.
> ```
> 
> Is this due to @ialarmedalien 's changes?

Nope, this was made before then, and I got too frustrated trying to get an SDK module to test with Travis. We should update it so it can actually run tests properly with @ialarmedalien's changes.

**Review by briehl — APPROVED** [review]
Looks fine. This just makes the Workspace mockable so tests can be better, right?

**Comment by MrCreosote** [comment]
Correct, you'll see it in action in the next PR

**Pull request merged**
