### PR TITLE
Fix None vs. int comparison bug

### PR DESCRIPTION
**Pull request by MrCreosote**
Public ticket: https://kbase-jira.atlassian.net/browse/PUBLIC-1411

Internal ticket: https://kbase-jira.atlassian.net/browse/PTV-1566

### CODE REVIEW

**Comment by MrCreosote** [comment]
has the same test failures as https://github.com/kbaseapps/StaticNarrative/pull/32

**Review by briehl — APPROVED** [review]
Thanks for the fix!

**Review by briehl — CHANGES_REQUESTED** [review]
Please bump the version in `kbase.yml`

**Review by briehl — APPROVED** [review]
👍

**Pull request merged**
